version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: farmer_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - farmer-net

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: farmer_manager
    env_file:
      - ./backend/.env.prod
    depends_on:
      - db
    networks:
      - farmer-net

volumes:
  pgdata:

networks:
  farmer-net:
    driver: bridge 